apiVersion: v3
entries:
  td-redis-operator:
  - apiVersion: "v3"
    appVersion: "0.2.0"
    created: "2022-12-09T18:31:59.43212871+08:00"
    urls:
    - https://github.com/tongdun/td-redis-operator/releases/download/0.2.0/td-redis-operator-0.2.0.tgz
    version: 0.2.0
    description: tongdun redis operator
    name: td-redis-operator
